export const enum ACTIONS {
	// system
	SYSTEM_REBOOT = "SYSTEM_REBOOT",

	// Queue
	QUEUE_CONSUME = "QUEUE_CONSUME",
	QUEUE_PUBLISH = "QUEUE_PUBLISH",

	// auth
	AUTH_LOGIN = "AUTH_LOGIN",
	AUTH_NEW_ACCOUNT_REGISTERED = "AUTH_NEW_ACCOUNT_REGISTERED",
	AUTH_ACCOUNT_ACTIVATED = "AUTH_ACCOUNT_ACTIVATED",
	AUTH_USER_PASSWORD_CHANGED = "AUTH_USER_PASSWORD_CHANGED",
}
