export const enum Actions {
	LOGIN = "LOGIN",
	NEW_ACCOUNT_REGISTERED = "NEW_ACCOUNT_REGISTERED",
	ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED",
	USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED",
	REBOOT = "REBOOT",
}
